"use client"

import React from "react"
import { motion } from "framer-motion"
import {
  User,
  MapPin,
  School,
  BookOpen,
  PhoneCall,
  FileCheck,
  UserPlus,
  ArrowRight,
  Sparkles,
  Upload,
  Mail,
  Smartphone,
  Info
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Badge } from "@/components/ui/badge"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"

export default function StudentsAdmissionsPage() {
  const [isSubmitting, setIsSubmitting] = React.useState(false)

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    setIsSubmitting(true)
    // Simulate API call
    setTimeout(() => setIsSubmitting(false), 2000)
  }

  return (
    <div className="flex flex-col gap-6 max-w-6xl mx-auto pb-20 animate-in fade-in slide-in-from-bottom-4 duration-500">

      {/* Header Section */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 px-1">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <div className="h-9 w-9 rounded-xl bg-primary/10 flex items-center justify-center">
              <UserPlus className="h-5 w-5 text-primary" />
            </div>
            <h1 className="text-2xl font-bold tracking-tight">Admission Enquiry</h1>
          </div>
          <p className="text-xs text-muted-foreground font-medium pl-11">Fill the form to create a new admission application.</p>
        </div>
        <div className="flex items-center gap-2 pl-11 md:pl-0">
          <Badge variant="outline" className="h-7 px-3 bg-primary/5 text-primary border-primary/20 font-bold text-[10px] tracking-widest gap-1.5 uppercase transition-all">
            <Sparkles className="h-3 w-3" />
            Session 2026-27
          </Badge>
        </div>
      </div>

      <Alert className="bg-primary/5 border-primary/20 text-primary rounded-2xl mx-1">
        <Info className="h-4 w-4 text-primary" />
        <AlertTitle className="text-xs font-bold uppercase tracking-wider">Note</AlertTitle>
        <AlertDescription className="text-[11px] font-medium opacity-80">
          Registration Number will be automatically generated by the system once the admission is approved.
        </AlertDescription>
      </Alert>

      <form onSubmit={handleSubmit} className="grid grid-cols-1 lg:grid-cols-3 gap-6">

        {/* Left Column - Main Details */}
        <div className="lg:col-span-2 space-y-6">

          {/* Section 1: Candidate Information */}
          <Card className="border-border/80 shadow-sm bg-card/50 backdrop-blur-sm overflow-hidden">
            <CardHeader className="p-5 border-b border-border/40 bg-muted/30">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-primary/10 text-primary">
                  <User className="h-4 w-4" />
                </div>
                <CardTitle className="text-sm font-bold">Candidate Details</CardTitle>
              </div>
            </CardHeader>
            <CardContent className="p-6 space-y-5">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                <div className="space-y-2">
                  <Label className="text-[11px] font-bold text-muted-foreground uppercase">Full Name</Label>
                  <div className="relative">
                    <User className="absolute left-3 top-2.5 h-3.5 w-3.5 text-muted-foreground/50" />
                    <Input placeholder="Enter full name" className="h-9 pl-9 text-sm focus-visible:ring-primary/20" required />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label className="text-[11px] font-bold text-muted-foreground uppercase">Email Address</Label>
                  <div className="relative">
                    <Mail className="absolute left-3 top-2.5 h-3.5 w-3.5 text-muted-foreground/50" />
                    <Input type="email" placeholder="example@cims.com" className="h-9 pl-9 text-sm focus-visible:ring-primary/20" required />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label className="text-[11px] font-bold text-muted-foreground uppercase">Phone Number</Label>
                  <div className="relative">
                    <Smartphone className="absolute left-3 top-2.5 h-3.5 w-3.5 text-muted-foreground/50" />
                    <Input placeholder="+91 00000 00000" className="h-9 pl-9 text-sm focus-visible:ring-primary/20" required />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label className="text-[11px] font-bold text-muted-foreground uppercase">Date of Birth</Label>
                  <Input type="date" className="h-9 text-sm" />
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Section 2: Address & Guardian */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card className="border-border/80 shadow-sm bg-card/50 backdrop-blur-sm overflow-hidden">
              <CardHeader className="p-4 border-b border-border/40 bg-muted/30">
                <CardTitle className="text-xs font-bold flex items-center gap-2">
                  <MapPin className="h-3.5 w-3.5 text-primary" /> Address
                </CardTitle>
              </CardHeader>
              <CardContent className="p-5">
                <div className="space-y-1.5">
                  <Label className="text-[10px] font-bold text-muted-foreground uppercase">Residential Address</Label>
                  <textarea
                    className="w-full min-h-[80px] rounded-lg border border-input bg-transparent px-3 py-2 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-primary/20"
                    placeholder="House No, Street, City..."
                  />
                </div>
              </CardContent>
            </Card>

            <Card className="border-border/80 shadow-sm bg-card/50 backdrop-blur-sm overflow-hidden">
              <CardHeader className="p-4 border-b border-border/40 bg-muted/30">
                <CardTitle className="text-xs font-bold flex items-center gap-2">
                  <PhoneCall className="h-3.5 w-3.5 text-primary" /> Guardian info
                </CardTitle>
              </CardHeader>
              <CardContent className="p-5 space-y-4">
                <div className="space-y-1.5">
                  <Label className="text-[10px] font-bold text-muted-foreground uppercase">Guardian Name</Label>
                  <Input placeholder="Father/Mother name" className="h-9 text-sm" />
                </div>
                <div className="space-y-1.5">
                  <Label className="text-[10px] font-bold text-muted-foreground uppercase">Relationship</Label>
                  <Input placeholder="Fatner, Brother..." className="h-9 text-sm" />
                </div>
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Right Column - Academic & Submit */}
        <div className="space-y-6">
          <Card className="border-border/80 shadow-sm bg-card/50 backdrop-blur-sm overflow-hidden">
            <CardHeader className="p-5 border-b border-border/40 bg-muted/30">
              <CardTitle className="text-sm font-bold flex items-center gap-3">
                <div className="p-2 rounded-lg bg-primary/10 text-primary">
                  <School className="h-4 w-4" />
                </div>
                Education History
              </CardTitle>
            </CardHeader>
            <CardContent className="p-6 space-y-4">
              <div className="space-y-1.5">
                <Label className="text-[11px] font-bold text-muted-foreground uppercase">Latest Qualification</Label>
                <Input placeholder="e.g. 10th, 12th, Graduate" className="h-9 text-sm" />
              </div>
              <div className="space-y-1.5">
                <Label className="text-[11px] font-bold text-muted-foreground uppercase">Interested Course</Label>
                <Select>
                  <SelectTrigger className="h-9 text-sm">
                    <SelectValue placeholder="Select Course" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="web">Fullstack Web Dev</SelectItem>
                    <SelectItem value="ds">Data Science Master</SelectItem>
                    <SelectItem value="uiux">UI/UX Design</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </CardContent>
          </Card>

          {/* Document Upload Simulation */}
          <Card className="border-border/80 shadow-sm bg-card/50 backdrop-blur-sm border-dashed">
            <CardContent className="p-6">
              <div className="flex flex-col items-center justify-center border-2 border-dashed border-border/60 rounded-2xl py-8 px-4 bg-muted/20 group hover:bg-primary/5 hover:border-primary/30 transition-all cursor-pointer">
                <Upload className="h-8 w-8 text-muted-foreground group-hover:text-primary transition-colors mb-2" />
                <p className="text-xs font-bold">Upload Documents</p>
                <p className="text-[9px] text-muted-foreground mt-1">PDF, JPG or PNG (Max 5MB)</p>
              </div>
            </CardContent>
          </Card>

          {/* Submission Card */}
          <Card className="border-none bg-gradient-to-br from-primary/90 to-primary text-white shadow-xl p-6 overflow-hidden relative">
            <div className="relative z-10 flex flex-col gap-5">
              <div className="space-y-1">
                <p className="text-[10px] font-black uppercase tracking-widest text-white/70">Action Required</p>
                <p className="text-base font-bold">Process Application</p>
                <p className="text-[11px] text-white/80 font-medium leading-relaxed">Review the enquiry data before submission. This will alert the admin for approval.</p>
              </div>
              <Button
                type="submit"
                disabled={isSubmitting}
                className="w-full h-11 bg-white text-primary rounded-xl font-black text-[12px] tracking-widest hover:bg-white/95 active:scale-95 transition-all shadow-xl"
              >
                {isSubmitting ? "PROCESSING..." : "SUBMIT ENQUIRY"}
                {!isSubmitting && <ArrowRight className="ml-2 h-4 w-4" />}
              </Button>
            </div>
            <div className="absolute -top-12 -right-12 h-40 w-40 bg-white/10 rounded-full blur-3xl opacity-50" />
            <div className="absolute -bottom-12 -left-12 h-32 w-32 bg-black/10 rounded-full blur-3xl opacity-50" />
          </Card>
        </div>

      </form>
    </div>
  )
}
